name: 'Notify the job summary to Slack'
description: 'This action notifies the job summary to Slack.'
author: 'Jumpei Matsuda'
branding:
  icon: 'alert-circle'
  color: 'gray-dark'
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  webhook-url:
    required: true
    description: "Slack webhook URL"
  channel:
    required: false
    default: ''
    description: "The channel id or name to notify. Use the default channel unless specified."
  author:
    required: false
    default: github-actions
    description: "The message author"
  author-icon-emoji:
    required: false
    default: ""
    description: "The message author icon (emoji)"
  content-template:
    required: false
    default: ""
    description: "a mds/ejs template to add the additional markdown content. Either one of this and content-template-path can be specified."
  content-template-path:
    required: false
    default: ""
    description: "a path to mds/ejs template to add the additional markdown content. Either one of this and content-template can be specified."
  show-default-title:
    required: false
    default: "true"
    description: "show the title of the default message. workflow name, repo slug, job status will be added to metadata instead if turned off."
  show-runner-metadata:
    required: false
    default: "true"
    description: "show arch, os, runner name or not"
  job-status:
    required: false
    default: ${{ job.status }}
    description: "You do not have to modify this property"
outputs:
  payload:
    description: the built payload. (stringified JSON object)
  response:
    description: the response body from Slack
  status-code:
    description: the response status code from Slack
  ok:
    description: '"true" if the request succeeded, otherwise "false"'
