name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: awk ./.github/mock_server.gawk &
      - uses: ./
        id: test
        with:
          webhook-url: http://localhost:8080
      - run: exit 0
        if: ${{ steps.test.outputs.ok == 'true' }}
      - run: exit 1
        if: ${{ steps.test.outputs.ok != 'true' }}
