name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    services:
      mock-server:
        image: jmatsu/stub-nginx-for-notify-job-summary:latest
        ports:
          - 8080:80
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: "with minimum requirements"
        id: test
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL || 'http://localhost:8080' }}
      - run: |
          cat<<EOF
          ${{ toJSON(steps.test.outputs) }}
          EOF
      - run: exit 0
        if: ${{ steps.test.outputs.ok == 'true' }}
      - run: exit 1
        if: ${{ steps.test.outputs.ok != 'true' }}
      - uses: ./
        id: content-template
        name: "with content-template"
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL || 'http://localhost:8080' }}
          content-template: ":right-facing_fist: <%= job.status %>"
          job-status: "This value has been embedded by the template"
      - uses: ./
        name: "with content-template-path"
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL || 'http://localhost:8080' }}
          content-template-path: ".github/templates/sample.md"
          job-status: "Hello from template"
      - run: exit 1
        continue-on-error: true
      - uses: ./
        name: "success after continue-on-error"
        if: >
          success()
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL || 'http://localhost:8080' }}
          channel: "random"
          content-template: "success after continue-on-error"
      - uses: ./
        name: "failure after continue-on-error"
        if: >
          failure()
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL || 'http://localhost:8080' }}
          channel: "random"
          content-template: "failure after continue-on-error"
      - uses: ./
        name: "notifications on every execution with changing the author information"
        if: >
          always()
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL || 'http://localhost:8080' }}
          channel: "C0G4GS22F"
          author: "any-name-you-want"
          author-icon-emoji: ":ok:"
          content-template: "this would always be shown"
